### ISSUE TITLE
glDatePicker fails to hide when focus is lost and on event.keycode = 13

### ISSUE THREAD

**Issue by coachroebuck** [glad/glDatePicker#31]
Hi!

Great tool... but the glDatePicker fails to hide when the focus is removed from the element, and when I hit the ENTER key. I can fix this, but you may want to know this for future releases.

Thanks for your efforts!

**Comment by coachroebuck** [comment]
You can append this to line 62 of the glDatePicker.min.js file, inside the "var O = function () { ... ". This catches the ENTER and TAB keystrokes. Hope this helps:

 }).keydown(function(event) {   //2012-02-24 Thanks Coach Roebuck! www.coachroebuck.com
                if(event.keyCode == 13 || event.keyCode == 9)
                {
                    d.hide(b);
                }
            });

**Comment by coachroebuck** [comment]
This isn't an issue...

I've updated your awesome library to further suit my purposes. I've beefed up the keydown event and attached IDs to both drop down lists. If you're interested, I'd be more than happy to pass you the udpated glDatePicker.min.js file. The pleasure would be mine.

Thanks!!

**Comment by glad** [comment]
coachroebuck,

Sorry I didn't respond earlier but thanks for the update.  Glad to hear you were able to resolve it. :)

BTW, the glDatePicker.min.js file is auto generated so any code you suggest, can you apply it in the glDatePicker.js file so that others can benefit too? :)

Also I've used this service to produce the .min.js file:
http://closure-compiler.appspot.com/home
